"use client";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { useNoteKoriStore } from "@/store/useNoteKoriStore";
import { CATEGORY_STYLES } from "@/lib/utils";
import type { AnalysisResult, HighlightCategory } from "@/lib/types";

const ORDER: HighlightCategory[] = [
  "important",
  "definition",
  "difficult",
  "understood",
];

/**
 * Hidden on screen, rendered only by the print stylesheet. This is what
 * "Download PDF" produces via the browser's print-to-PDF, which keeps Bangla
 * shaping intact because the system font stack does the rendering.
 */
export function PrintableReport({ result }: { result: AnalysisResult }) {
  const highlights = useNoteKoriStore((state) => state.highlights);

  return (
    <div className="print-root hidden print:block">
      <header className="mb-8 border-b border-gray-300 pb-5">
        <h1 className="text-3xl font-bold">{result.title}</h1>
        <p className="mt-2 text-sm">
          {result.subject}
          {result.languages.length > 0 && ` · ${result.languages.join(", ")}`}
          {` · Confidence ${Math.round(result.confidence_score * 100)}%`}
        </p>
        <p className="mt-1 text-xs">Generated by NoteKori</p>
      </header>

      {result.clean_notes && (
        <section className="print-section mb-8">
          <div className="prose-notekori max-w-none">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{result.clean_notes}</ReactMarkdown>
          </div>
        </section>
      )}

      {result.bangla_explanation && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">সহজ বাংলা ব্যাখ্যা</h2>
          <div className="bangla prose-notekori max-w-none">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {result.bangla_explanation}
            </ReactMarkdown>
          </div>
        </section>
      )}

      {result.key_concepts.length > 0 && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Key Concepts</h2>
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr>
                <th className="border p-2 text-left">Concept</th>
                <th className="border p-2 text-left">Definition</th>
              </tr>
            </thead>
            <tbody>
              {result.key_concepts.map((concept, index) => (
                <tr key={index}>
                  <td className="border p-2 font-medium">{concept.name}</td>
                  <td className="border p-2">{concept.definition}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      {result.code_blocks.length > 0 && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Code</h2>
          {result.code_blocks.map((block, index) => (
            <div key={index} className="avoid-break mb-4">
              {block.original_code && (
                <>
                  <p className="mb-1 text-xs font-medium">As written on the board</p>
                  <pre className="mb-2 whitespace-pre-wrap p-3 text-xs">
                    <code>{block.original_code}</code>
                  </pre>
                </>
              )}
              {block.corrected_code && block.corrected_code !== block.original_code && (
                <>
                  <p className="mb-1 text-xs font-medium">Corrected</p>
                  <pre className="mb-2 whitespace-pre-wrap p-3 text-xs">
                    <code>{block.corrected_code}</code>
                  </pre>
                </>
              )}
              {block.explanation && <p className="text-sm italic">{block.explanation}</p>}
            </div>
          ))}
        </section>
      )}

      {result.uncertain_content.length > 0 && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Uncertain Content</h2>
          <ul className="list-disc pl-5 text-sm">
            {result.uncertain_content.map((item, index) => (
              <li key={index} className="mb-1">
                {item.text}{" "}
                <span className="text-xs">
                  ({Math.round(item.confidence * 100)}% — {item.reason})
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {result.mermaid && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Mind Map</h2>
          <pre className="whitespace-pre-wrap p-3 text-xs">
            <code>{result.mermaid}</code>
          </pre>
        </section>
      )}

      {result.flashcards.length > 0 && (
        <section className="print-page-break print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Flashcards</h2>
          <ol className="list-decimal pl-5 text-sm">
            {result.flashcards.map((card) => (
              <li key={card.id} className="avoid-break mb-3">
                <p className="bangla font-medium">{card.question}</p>
                <p className="bangla mt-0.5">{card.answer}</p>
                <p className="text-xs">
                  {card.difficulty}
                  {card.topic && ` · ${card.topic}`}
                </p>
              </li>
            ))}
          </ol>
        </section>
      )}

      {result.quiz.length > 0 && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Quiz</h2>
          <ol className="list-decimal pl-5 text-sm">
            {result.quiz.map((question, index) => (
              <li key={index} className="avoid-break mb-3">
                <p className="bangla font-medium">{question.question}</p>
                <ul className="list-disc pl-5">
                  {question.options.map((option) => (
                    <li key={option} className="bangla">
                      {option}
                    </li>
                  ))}
                </ul>
                <p className="bangla mt-1 text-xs">
                  <strong>Answer:</strong> {question.correct_answer} — {question.explanation}
                </p>
              </li>
            ))}
          </ol>
        </section>
      )}

      {result.exam_questions.length > 0 && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">Exam Questions</h2>
          <ol className="list-decimal pl-5 text-sm">
            {result.exam_questions.map((question, index) => (
              <li key={index} className="avoid-break mb-2">
                <span className="bangla font-medium">{question.question}</span>{" "}
                <span className="text-xs">({question.marks} marks)</span>
                {question.answer_outline && (
                  <p className="bangla mt-0.5 text-xs">{question.answer_outline}</p>
                )}
              </li>
            ))}
          </ol>
        </section>
      )}

      {result.revision_summary && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">One-Minute Revision</h2>
          <div className="bangla prose-notekori max-w-none text-sm">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {result.revision_summary}
            </ReactMarkdown>
          </div>
        </section>
      )}

      {highlights.length > 0 && (
        <section className="print-section mb-8">
          <h2 className="mb-3 text-xl font-semibold">My Highlights</h2>
          {ORDER.map((category) => {
            const items = highlights.filter((h) => h.category === category);
            if (items.length === 0) return null;

            return (
              <div key={category} className="mb-3">
                <h3 className="mb-1 font-medium">{CATEGORY_STYLES[category].label}</h3>
                <ul className="list-disc pl-5 text-sm">
                  {items.map((highlight) => (
                    <li key={highlight.id} className="bangla">
                      {highlight.selected_text}
                    </li>
                  ))}
                </ul>
              </div>
            );
          })}
        </section>
      )}
    </div>
  );
}
