from collections import defaultdict

from app.schemas.analysis import AnalysisResult
from app.schemas.highlight import Highlight

CATEGORY_TITLES = {
    "important": "Important",
    "definition": "Definitions",
    "difficult": "Difficult",
    "understood": "Understood",
}


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body}\n"


def build_markdown(result: AnalysisResult, highlights: list[Highlight]) -> str:
    parts: list[str] = [
        f"# {result.title}\n",
        f"> **Subject:** {result.subject}  ",
        f"> **Languages:** {', '.join(result.languages) or 'Not detected'}  ",
        f"> **Overall confidence:** {result.confidence_score:.0%}  ",
        "> **Generated by:** NoteKori\n",
        "---\n",
    ]

    if result.clean_notes:
        parts.append(_section("Study Guide", result.clean_notes))

    if result.bangla_explanation:
        parts.append(_section("সহজ বাংলা ব্যাখ্যা", result.bangla_explanation))

    if result.key_concepts:
        rows = "\n".join(
            f"| {c.name} | {c.definition} |" for c in result.key_concepts
        )
        parts.append(
            _section(
                "Key Concepts",
                f"| Concept | Definition |\n| --- | --- |\n{rows}",
            )
        )

    if result.code_blocks:
        blocks = []
        for index, block in enumerate(result.code_blocks, start=1):
            entry = [f"### Code Block {index}\n"]
            if block.original_code:
                entry.append(f"**As written on the board:**\n\n```{block.language}\n{block.original_code}\n```\n")
            if block.corrected_code:
                entry.append(f"**Corrected:**\n\n```{block.language}\n{block.corrected_code}\n```\n")
            if block.explanation:
                entry.append(f"*{block.explanation}*\n")
            blocks.append("\n".join(entry))
        parts.append(_section("Code", "\n".join(blocks)))

    if result.uncertain_content:
        rows = "\n".join(
            f"| {u.text} | {u.confidence:.0%} | {u.reason} |" for u in result.uncertain_content
        )
        parts.append(
            _section(
                "Uncertain Content",
                "These passages were unclear in the source image. Verify them against "
                "your own notes.\n\n"
                f"| Detected text | Confidence | Reason |\n| --- | --- | --- |\n{rows}",
            )
        )

    if result.mermaid:
        parts.append(_section("Mind Map", f"```mermaid\n{result.mermaid}\n```"))

    if result.flashcards:
        cards = "\n".join(
            f"**{index}. {card.question}**  \n"
            f"<details><summary>Show answer</summary>\n\n{card.answer}\n\n</details>  \n"
            f"`{card.difficulty}` `{card.topic}`\n"
            for index, card in enumerate(result.flashcards, start=1)
        )
        parts.append(_section("Flashcards", cards))

    if result.quiz:
        questions = []
        for index, question in enumerate(result.quiz, start=1):
            options = "\n".join(f"- {option}" for option in question.options)
            questions.append(
                f"**{index}. {question.question}**\n\n{options}\n\n"
                f"<details><summary>Answer</summary>\n\n"
                f"**{question.correct_answer}** — {question.explanation}\n\n</details>\n"
            )
        parts.append(_section("Quiz", "\n".join(questions)))

    if result.exam_questions:
        items = "\n".join(
            f"{index}. **({q.marks} marks)** {q.question}\n   - {q.answer_outline}"
            for index, q in enumerate(result.exam_questions, start=1)
        )
        parts.append(_section("Exam Questions", items))

    if result.revision_summary:
        parts.append(_section("One-Minute Revision", result.revision_summary))

    if highlights:
        grouped: dict[str, list[Highlight]] = defaultdict(list)
        for highlight in highlights:
            grouped[highlight.category].append(highlight)

        body = []
        for category, items in grouped.items():
            body.append(f"### {CATEGORY_TITLES.get(category, category.title())}\n")
            body.extend(f"- {item.selected_text}" for item in items)
            body.append("")
        parts.append(_section("My Highlights", "\n".join(body)))

    if result.extracted_text:
        parts.append(
            _section("Raw Extracted Text", f"```text\n{result.extracted_text}\n```")
        )

    return "\n".join(parts)


def build_filename(title: str, extension: str) -> str:
    safe = "".join(char if char.isalnum() else "_" for char in title).strip("_")
    safe = "_".join(filter(None, safe.split("_")))[:60] or "Notes"
    return f"NoteKori_{safe}.{extension}"
